### ISSUE TITLE
Any network files available? 

### ISSUE THREAD

**Issue by jolespin** [CovertLab/WholeCellEcoliRelease#5]
I was wondering if there were any network files available from https://science.sciencemag.org/content/369/6502/eaav3751.editor-summary that I could load into cytoscape or networkx?

**Comment by tahorst** [comment]
Currently, we don't export any data for those packages so you would have to generate the network files yourself.  Is there something in particular that you are interested in?  I might be able to point you towards the relevant data in our data structure for you to generate the files you want.

**Comment by jolespin** [comment]
Thanks for getting back to me.  So essentially what I’m looking for is some sort of network structure I can use as a scaffold for an E. Coli network. Preferably the format would be (source, target, weight) or even just (source, target) so I can see which genes are connected to what.  Does this overlap with the models from your study or is this out of scope?

**Comment by tahorst** [comment]
You would need to build something like that yourself but you should be able to build it with the data files we have.  It would require piecing together several files or data representations though since we don't have a network of the entire cell readily specified in the code or data files.  This is something that we will likely include in a future release with another publication.
